---
- name: Check if we need to install python
  delegate_to: "{{ item.name }}"
  raw: "if [ -f /usr/bin/dpkg ]; then dpkg -s python; else :; fi"
  register: python_install_check
  failed_when: python_install_check.rc not in [0, 1]
  changed_when: no

- name: Install python
  delegate_to: "{{ item.name }}"
  raw: apt-get install -y python
  when: "{{ python_install_check.rc }} != 0"
